#!/usr/bin/env python  
#-*- coding: utf-8 -*-
import MySQLdb
import urllib
import time
import re
n=15
k=2
url=['']*n
timu=['']*n
shijian=['']*n
page=1

while page<=22:
 con=urllib.urlopen('http://www.3w3n.com/marketInfo/showMarketInfoList?pageNo='+str(page)+'&category=分析预测&Sun%20Jul%2030%202017%2009:38:03%20GMT+0800%20(中国标准时间)').read()
 i=0
 href=con.find(r'onclick="window.open(')
 title=con.find(r'农产品价格信息网-农价云',href)
 time=con.find(r'<div class="sc_time">',title)
 end=con.find(r'</div>',time)
 while title !=-1 and href != -1 and time != -1 and i<n:
    url[i]=con[href+22:title-3].strip()
    timu[i]=con[title+38:time-14].strip()
    href=con.find(r'onclick="window.open(',time)
    shijian[i]=con[time+21:end].strip()
    
    title=con.find(r'农产品价格信息网-农价云',href)
    time=con.find(r'<div class="sc_time">',title)
    end=con.find(r'</div>',time)
    i=i+1
 else:
    print page,'find end'

 j=0
 type=0;
 while j<15:
    
    content=urllib.urlopen('http://www.3w3n.com'+url[j]).read()
    
    title=content.find(r'<div class="title">')
    titleend=content.find(r'</div>',title)
    time=content.find(r'时间')
    timeend=content.find(r'</span>',time)
    laiyuan=content.find(r'<span>来源',timeend)
    laiyuanend=content.find(r'</span>',laiyuan)
    t1=content.find(r'<div class="content">')
    t2=content.find(r'</div>',t1)
    titl=content[title+19:titleend]
    timet=content[time+9:timeend]
    ly=content[laiyuan+15:laiyuanend]
    tt=content[t1:t2]
    
    if __name__ == '__main__':  
     p = re.compile('<[^>]+>')
     wen1=p.sub("",titl)
     wen2=tt
     wen3=p.sub("",timet)
     wen4=p.sub("",ly)
     print wen1+' '+wen2+' '+wen3+' '+wen4
     conn=MySQLdb.connect(host='localhost',user='root',passwd='sa',db='bzsjpt',port=3306,charset='utf8')

     cur=conn.cursor()
     sqli="insert into fxyc values(%s,%s,%s,%s,%s )"
     
     cur.execute(sqli,(k,wen1.strip(),wen2.strip(),timet.strip(),ly.strip()))
     
 
     conn.commit()
     cur.close()
     conn.close()
    j=j+1
    k=k+1

 page=page+1;




